### ISSUE TITLE
Move to jenkinsci / transfer ownership?

### ISSUE THREAD

**Issue by timja** [jenkinsci/access-modifier#30]
See https://github.com/kohsuke/access-modifier/pull/18#issuecomment-646310012

cc @oleg-nenashev @kohsuke @jglick

Need to decide whether he publish to jenkinsci only, get OSSRH access, or update group ID and publish under a new name to OSSRH

@slide

**Comment by jglick** [comment]
Moving the repo (or just forking it) is one thing, but then we need to either get OSSRH access, or start publishing to Jenkins Artifactory only.

**Comment by oleg-nenashev** [comment]
Yes. FTR https://groups.google.com/g/jenkinsci-dev/c/swwZyd_1wO0/m/aANx4jQmAgAJ 
I think that forking and changing destination would be good for now. I wish we made more progress with hosting though

**Comment by timja** [comment]
no issue with hosting this for me,

Main question is do we only publish to jenkins ci, or do we get OSSRH too?

**Comment by timja** [comment]
Other question is do we try get it transferred or just fork?

**Comment by kohsuke** [comment]
Let me know how you guys decide in the end.

**Comment by oleg-nenashev** [comment]
I am +1 for transfer. There are only a few usages outside Jenkins, so I'd
guess moving to the Jenkins Maven repo is acceptable. We also have a few
core contributors with OSSRH accounts if we want to deploy there

**Comment by timja** [comment]
+1 for transfer

I have a small preference to continue publishing in OSSRH, but if it's too much effort we can skip

**Comment by timja** [comment]
Shall we just transfer it, publish to repo.jenkins-ci.org for now.

We can always publish to central later if desired?

**Comment by daniel-beck** [comment]
This has tons of forks already, so the regular fork & delete model isn't great. It would also lose, or distribute, issues and PRs.

I recommend this be transferred. KK can just transfer to `jenkinsci`, and we can fix up the repo configuration afterwards as needed. This should also setup a redirect from this repo's URL to jenkinsci/access-modifier.

**Comment by kohsuke** [comment]
Done

**Comment by oleg-nenashev** [comment]
Thank you!

**Comment by timja** [comment]
Thanks! I've granted jenkinsci/core admin access and raised https://github.com/jenkinsci/access-modifier/issues/31 for CI
